version: "3"

networks:
  traefik_default:
    external: true

services:
  laravel5_php7:
    image: "hypertd/laravel-php7-2:latest"
    deploy:
        labels:
            - "traefik.port=80"
            - "traefik.docker.network=traefik_default"
            - "traefik.frontend.rule=Host:${DEV_SUBDOMAIN}.dev.hypertd.com"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.redirect=https"
            - "traefik.frontend.redirect.entryPoint=https"
    networks:
      - traefik_default
    volumes:
      - data:/var/www/html
      
volumes:
    data:
      driver: local-persist
      driver_opts:
        mountpoint: /mnt/docker-volumes/dev-${DEV_SUBDOMAIN}